# [[manager.prepend_keymap]]
# on   = "T"
# run  = "plugin max-preview"
# desc = "Maximize or restore preview"

# Hide preview plugin # 
[[manager.prepend_keymap]]
on   = "T"
run  = "plugin hide-preview"
desc = "Hide or show preview"

# Archiver files plugin #
[[manager.prepend_keymap]]
on   = [ "A", "c" ]
run  = "plugin compress"
desc = "Archive selected files"

# Copy file to system-clipboard #
[[manager.prepend_keymap]]
on   = [ "c", "y" ]
run  = ["plugin system-clipboard"]
desc = "Copy to system-clipboard"

# Copy contents of files #
[[manager.prepend_keymap]]
on = [ "c", "a" ]
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

